main: survivalislands.SurvivalIslands
name: Survival-Islands
version: 1.0.0
author: PublicGameCoder
depend: [WorldEdit, Citizens, Vault]

commands:
   SurvivalIsland:
      description: The SurvivalIsland's help command!
      permission: SurvivalIsland.User
   SI:
      description: The SurvivalIsland's help command!
      permission: SurvivalIsland.User
   SIM:
      description: Access your Manager externally!
      permission: SurvivalIsland.Manager.Anywhere
   SIR:
      description: Reloads the SurvivalIsland Plugin!
      permission: SurvivalIsland.Admin